name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      testFiles:
        description: 'Specify test files or pattern to run (e.g., tests/user.spec.ts or tests/api/*.ts)'
        required: false
        default: ''
env:
  GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        if [ -z "${{ github.event.inputs.testFiles }}" ]; then
          echo "Running all tests..."
          npx playwright test 
        else
          echo "Running specified test files: ${{ github.event.inputs.testFiles }}"
          npx playwright test ${{ github.event.inputs.testFiles }}
        fi
      env:
        GOREST_TOKEN : ${{secrets.GOREST_TOKEN}}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
